### ISSUE TITLE
Blocksparse is not available: the current GPU does not expose Tensor cores

### ISSUE THREAD

**Issue by scarygliders** [SerCeMan/fontogen#2]
Attempting to run this using my nvidia RTX 2070 Super (Turing architecture), which can run other stuff like stable-diffusion-webui or koboldcpp just fine...

```
> python server.py
Blocksparse is not available: the current GPU does not expose Tensor cores
Traceback (most recent call last):
  File "path/fontogen/server.py", line 10, in <module>
    from sampler import create_sampler
  File "path/fontogen/sampler.py", line 11, in <module>
    from model.model import FontogenModule
  File "path/fontogen/model/model.py", line 11, in <module>
    from xformers.components.attention import BlockSparseAttention
ImportError: cannot import name 'BlockSparseAttention' from 'xformers.components.attention' (path/.virtualenvs/fontogen-Ir94UGpw/lib/python3.10/site-packages/xformers/components/attention/__init__.py)
```

Looking at the [Blocksparse](https://github.com/openai/blocksparse) information, the nvidia Turing architecture isn't mentioned, so perhaps I am unable to try out fontogen?

**Comment by behdad** [comment]
I followed the instructions on the homepage and hit this same error.

**Comment by mpybkk** [comment]
This is where I am at also, on RTX 3090 Ti and looking to test out some training. 
Windows 10, also can run Stable Diffusion / Automatic111. 

Any ideas how to resolve this?

**Comment by sfdgdfh** [comment]
hello everyone, anyone resolve this?

**Comment by sfdgdfh** [comment]
maybe xformers's version is not match cuda or torch, I solved the issue with cuda11.8 and torch 2.1.0
